### ISSUE TITLE
Breakdown of Model

### ISSUE THREAD

**Issue by alphabin** [ChuckBerryOnTop/cobrakai#12]
| Description | 
The model is where we have our database mutators, it will update and query the data using 
Sequelize  

| Tasks|

1. Set Up the database using Sequilize 
2. Create a table UserInfo = [TimeStamp, EncodedData,GoogleApiObject]
3. Create a method that is exportable using require(somename.js), in this we should have mutator functions that let us add a 
##1. New entry into the UserInfo table.
##2. Delete entry from the UserInfo table

| Estimate | 
16 hrs

| Spending Effort |

| Blocked |

**Comment by jeffreylee87** [comment]
Created basic model using sequelize and created basic table for us to start out. Current model holds image and name columns. Timestamp and id are automatic with sequelize.
